---
  - name: Install HTTPD
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon"

  - name: start Httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"

  - name: Enable Httpd
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon"


- name: Install HTTP Server
  hosts: g1
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: start Apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Amazon"

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Amazon"

...